<?php

/**
 * BaseCategoryArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $article_id
 * @property Article $Article
 * @property Category $Category
 * 
 * @method integer         getCategoryId()  Returns the current record's "category_id" value
 * @method integer         getArticleId()   Returns the current record's "article_id" value
 * @method Article         getArticle()     Returns the current record's "Article" value
 * @method Category        getCategory()    Returns the current record's "Category" value
 * @method CategoryArticle setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryArticle setArticleId()   Sets the current record's "article_id" value
 * @method CategoryArticle setArticle()     Sets the current record's "Article" value
 * @method CategoryArticle setCategory()    Sets the current record's "Category" value
 * 
 * @package    doublebow
 * @subpackage model
 * @author     Piotr Kubica
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_article');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'article_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'category_id',
             'onDelete' => 'CASCADE'));
    }
}