<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/12 11:04:13
sfConfig::add(array(
  'app_max_articles_on_page' => 5,
  'app_rss_max_items' => 25,
  'app_col_cnt_404' => 3,
  'app_min_items_in_col_404' => 5,
));
