<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/12 11:04:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=d2bow_prod',
  'username' => 'd2bow_client',
  'password' => '***REMOVED***',
  'name' => 'doctrine',
)),);
