<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/06/12 11:22:05
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'C:/symfony-1.4.6/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseform' => 'C:/wamp/www/doublebow/private_html/lib/form/BaseForm.class.php',
  'commentform' => 'C:/wamp/www/doublebow/private_html/lib/form/CommentForm.class.php',
  'searchform' => 'C:/wamp/www/doublebow/private_html/lib/form/SearchForm.php',
  'arrayoptimizer' => 'C:/wamp/www/doublebow/private_html/lib/pk8Utils/ArrayOptimizer.class.php',
  'pager' => 'C:/wamp/www/doublebow/private_html/lib/pk8Utils/Pager.class.php',

  // project_model
  'article' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/Article.class.php',
  'articletable' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/ArticleTable.class.php',
  'author' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/Author.class.php',
  'authortable' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/AuthorTable.class.php',
  'basearticle' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/base/BaseArticle.class.php',
  'baseauthor' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/base/BaseAuthor.class.php',
  'basecategory' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/base/BaseCategory.class.php',
  'basecategoryarticle' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/base/BaseCategoryArticle.class.php',
  'basecomment' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/base/BaseComment.class.php',
  'category' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/Category.class.php',
  'categoryarticle' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/CategoryArticle.class.php',
  'categoryarticletable' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/CategoryArticleTable.class.php',
  'categorytable' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/CategoryTable.class.php',
  'comment' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/Comment.class.php',
  'commenttable' => 'C:/wamp/www/doublebow/private_html/lib/model/doctrine/CommentTable.class.php',

  // application
  'myuser' => 'C:/wamp/www/doublebow/private_html/apps/frontend/lib/myUser.class.php',

  // modules
);
