<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/12 11:04:14
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'DoubleBow - Web Developer&#039;s Blog', false, false);
  $response->addMeta('description', 'My personal web blog about programming, web development and IT overall', false, false);
  $response->addMeta('keywords', 'doublebow, javascript, actionscript, PHP, HTML, CSS, XML, MySQL, Java, programming, web, developers, development, blog', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('author', 'Piotr Kubica', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('fonts.css', '', array ());
  $response->addStylesheet('grid.css', '', array ());
  $response->addStylesheet('style.css', '', array ());


